### ISSUE TITLE
Node js v8 throws babel error trezor.js v6.17.6

### ISSUE THREAD

**Issue by Ch1p999** [trezor/trezor.js#68] opened 2018-07-26 06:31 UTC
Please advice 

Code
```
'use strict';

// installed from npm
var trezor = require('trezor.js');

var debug = true;
var list = new trezor.DeviceList();

console.log(list)
```

```
module.js:487
    throw err;
    ^

Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/trezor-node-app/node_modules/trezor.js/lib/session.js:8:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

```

**Comment by Ch1p999** [comment] 2018-07-26 06:40
Worked when I installed babel-runtime but it says connected yet throws this error 
```
 name: 'FetchError',
  message: 'request to https://localback.net:21324 failed, reason: connect ECONNREFUSED 127.0.0.1:21324',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
```

**Comment by prusnak** [comment] 2018-07-26 10:12
Duplicate of https://github.com/trezor/trezor.js/issues/48 and https://github.com/trezor/trezor.js/issues/59

@Ch1p999 please use master or wait for the next 7.x release

**Closed by prusnak** 2018-07-26 10:12 UTC
