### ISSUE TITLE
Connected 'unacquired'

### ISSUE THREAD

**Issue by axic** [trezor/trezor.js#22] opened 2016-03-02 22:13 UTC
I am wondering if this is desired behaviour or I am doing something wrong. Pages shouldn't be refreshed while being connected, but it can and will happen.

I have the following scenario (using code based on the 'list example')
- Device is connected and displays the signMessage() state (`connect` is emitted)
- Cancel the signing with the button and wait till all the callbacks execute (the error catch in the promise is called)
- Do not disconnect the device
- Refresh browser page (e.g. reload the code)
- Issue: at this stage it won't be connected, see the messages below (`connect` is not emitted)
- Unplugging and plugging it again makes it to connect properly (it emits the `disconnect` event with an `undefined` device, then everything goes normal)

**After refreshing**:

```
[trezor] Attempting to load Chrome Extension transport at jcjjhjgimijdkoamemaghajlhegmoclj
trezor.js:1986 [trezor] Loaded Chrome Extension transport
trezor.js:346 Connected unacquired
```

And it just stays here, nothing will happen.

**After unplugging the Trezor**:

```
Disconnected a device: undefined
```

This is my callback on the `disconnect` event:

``` js
list.on('disconnect', function (device) {
    console.log('Disconnected a device:', device);
});
```

**After plugging in the Trezor again**:

```
[trezor] Sending Initialize Object {}
trezor.js:1728 [trezor] Received Features Object {vendor: "bitcointrezor.com", major_version: 1, minor_version: 2, patch_version: 1, bootloader_mode: null…}
trezor.js:1321 [trezor] Releasing session
app.js:123364 Connected a device: Device {_events: Object, _maxListeners: undefined, transport: ChromeExtensionTransport, path: 119, deviceList: DeviceList…}
app.js:123365 Devices: [Device]
trezor.js:1722 [trezor] Sending Initialize Object {}
trezor.js:1728 [trezor] Received Features Object {vendor: "bitcointrezor.com", major_version: 1, minor_version: 2, patch_version: 1, bootloader_mode: null…}
```

I guess in the unacquired state, it might be possible to do a cleanup (what would happen prior the disconnected event) to get it working?

**Comment by axic** [comment] 2016-03-02 22:29
Looking more into this. Can this be fixed or should I just prompt the user to disconnect/reconnect on `connectUnacquired`?

**Comment by runn1ng** [comment] 2016-03-03 12:53
Hey.

We are now making some more documentation draft explaining sessions and acquiring/releasing, but some of the code is to the new version that is not tested yet and we are still working on it (and on the docs)

The documentation of what we call "multitasking" is here, with pictures

https://github.com/trezor/trezor.js/tree/docs#multitasking

the point is, there is always acquire - (action) - release, and then someone else can use the device. 

The problem is - when you do reload in the middle of the action, release is never called.

There are two possible approaches:

* call `steal()` on the unacquiredDevice - that does it, but can interrupt some other action elsewhere (so you should do it only when user asks for it)
* or, what we try to do in mytrezor, is calling release on `window.onbeforeunload`. That method can, unfortunately, call only synchronous calls; that's why we have all these synchronous stuff in the API. Also it doesn't have to actually run; `window.onbeforeunload` are not guaranteed to finish (browser kills it after a while so it doesn't block the browser tab on closing/reloading); also calls to browser extension are asynchronous anyway; so it's all slightly hack-ish. What I want to say - even with releasing in `window.onbeforeunload`, you still might end up with `unacquiredDevice` unfortunately if you reload in the middle of an action.

Thanks for noticing that though. I will add something about this in the example.

**Comment by axic** [comment] 2016-03-03 13:16
Thanks @runn1ng for the explanation.

Is the following a safe bet then? (just the logic)

```js
list.on('connectUnacquired', function (device) {
  // ask the user if he wants to force acquire
  askUserForceAcquire(function(err, res) {
    if (res)
      device.steal()
  })
})
```

**Comment by runn1ng** [comment] 2016-03-03 13:17
Yep! That looks good.

**Comment by axic** [comment] 2016-03-03 13:31
Great! And after `steal()` I assume `connect` will be emitted as usual?

Also if I would want to implement the `window.onbeforeunload` cleanup, where should I look for the synchronous methods?

**Comment by runn1ng** [comment] 2016-03-03 14:07
> Great! And after steal() I assume connect will be emitted as usual?

Yes. Also, steal() should actually return promise that resolves with the new device. (But internally it's still implemented with `.on('connect')` so you are probably better using that.)

> Also if I would want to implement the window.onbeforeunload cleanup, where should I look for the synchronous methods?

I am now working on making them easier to use. I will let you know

> As a note to the multitasking documentation, you refer to events called unacquiredDevice and device, while currently it seems they are called connectUnacquired and connect.

Thanks, I will look at that.

Thanks for looking at the lib, it's great to have some feedback :)

**Comment by runn1ng** [comment] 2016-03-05 01:17
I fixed some issues and I added a function for the `onbeforeunload` cleanup, and also added it to the example.

**Comment by axic** [comment] 2016-03-06 00:26
@runn1ng thank you, I will give it a try tomorrow. The high level example looks pretty straightforward.

Would it make sense adding `steal()` to the lowlevel example too?

**Comment by runn1ng** [comment] 2016-03-06 10:34
The low level example is not using the deviceList / Device / UnacquiredDevice abstraction at all.

**Comment by axic** [comment] 2016-03-07 17:50
That makes sense. Steal and the sample code works well.

**Closed** 2018-06-18 20:23 UTC
